version: 2

models: # view ou tabelas
  - name: stg_commodities
    description: "Tabela de staging para dados de preços de commodities"
    columns:
      - name: data
        description: "Data da observação"
      - name: valor_fechamento
        description: "Preço de fechamento da commodity no dia"
      - name: ticker_code
        description: "Código do ativo"
  - name: stg_commodities_trade
    description: "Tabela de staging para dados de trading das commodities"
    columns:
      - name: data
        description: "Data da operação"
      - name: action
        description: "Tipo de operação realizada"
      - name: quantity
        description: "Quantidade negociada"
      - name: ticker_code
        description: "Código do ativo"